#!/bin/bash

bash calculate_annual_values_required_by_edward.sh 2000
bash calculate_annual_values_required_by_edward.sh 2001
bash calculate_annual_values_required_by_edward.sh 2002
bash calculate_annual_values_required_by_edward.sh 2003
bash calculate_annual_values_required_by_edward.sh 2004
bash calculate_annual_values_required_by_edward.sh 2005
bash calculate_annual_values_required_by_edward.sh 2006
bash calculate_annual_values_required_by_edward.sh 2007
bash calculate_annual_values_required_by_edward.sh 2008
bash calculate_annual_values_required_by_edward.sh 2009
bash calculate_annual_values_required_by_edward.sh 2010
bash calculate_annual_values_required_by_edward.sh 2011
bash calculate_annual_values_required_by_edward.sh 2012
bash calculate_annual_values_required_by_edward.sh 2013
bash calculate_annual_values_required_by_edward.sh 2014
bash calculate_annual_values_required_by_edward.sh 2015

