bash calculate_monthly_direct_runoff_contribution_from_urban_area.sh 1980 1980 &
bash calculate_monthly_direct_runoff_contribution_from_urban_area.sh 1981 1981 &
bash calculate_monthly_direct_runoff_contribution_from_urban_area.sh 1982 1982 &
bash calculate_monthly_direct_runoff_contribution_from_urban_area.sh 1983 1983 &
bash calculate_monthly_direct_runoff_contribution_from_urban_area.sh 1984 1984 &
bash calculate_monthly_direct_runoff_contribution_from_urban_area.sh 1985 1985 &
bash calculate_monthly_direct_runoff_contribution_from_urban_area.sh 1986 1986 &
bash calculate_monthly_direct_runoff_contribution_from_urban_area.sh 1987 1987 &
bash calculate_monthly_direct_runoff_contribution_from_urban_area.sh 1988 1988 &
bash calculate_monthly_direct_runoff_contribution_from_urban_area.sh 1989 1989 &
bash calculate_monthly_direct_runoff_contribution_from_urban_area.sh 1990 1990 &
bash calculate_monthly_direct_runoff_contribution_from_urban_area.sh 1991 1991 &
bash calculate_monthly_direct_runoff_contribution_from_urban_area.sh 1992 1992 &
bash calculate_monthly_direct_runoff_contribution_from_urban_area.sh 1993 1993 &
bash calculate_monthly_direct_runoff_contribution_from_urban_area.sh 1994 1994 &
bash calculate_monthly_direct_runoff_contribution_from_urban_area.sh 1995 1995 &
bash calculate_monthly_direct_runoff_contribution_from_urban_area.sh 1996 1996 &
bash calculate_monthly_direct_runoff_contribution_from_urban_area.sh 1997 1997 &
bash calculate_monthly_direct_runoff_contribution_from_urban_area.sh 1998 1998 &
bash calculate_monthly_direct_runoff_contribution_from_urban_area.sh 1999 1999 &
bash calculate_monthly_direct_runoff_contribution_from_urban_area.sh 2000 2000 &
bash calculate_monthly_direct_runoff_contribution_from_urban_area.sh 2001 2001 &
bash calculate_monthly_direct_runoff_contribution_from_urban_area.sh 2002 2002 &
bash calculate_monthly_direct_runoff_contribution_from_urban_area.sh 2003 2003 &
bash calculate_monthly_direct_runoff_contribution_from_urban_area.sh 2004 2004 &
bash calculate_monthly_direct_runoff_contribution_from_urban_area.sh 2005 2005 &
bash calculate_monthly_direct_runoff_contribution_from_urban_area.sh 2006 2006 &
bash calculate_monthly_direct_runoff_contribution_from_urban_area.sh 2007 2007 &
bash calculate_monthly_direct_runoff_contribution_from_urban_area.sh 2008 2008 &
bash calculate_monthly_direct_runoff_contribution_from_urban_area.sh 2009 2009 &
bash calculate_monthly_direct_runoff_contribution_from_urban_area.sh 2010 2010 &
bash calculate_monthly_direct_runoff_contribution_from_urban_area.sh 2011 2010 &
bash calculate_monthly_direct_runoff_contribution_from_urban_area.sh 2012 2010 &
bash calculate_monthly_direct_runoff_contribution_from_urban_area.sh 2013 2010 &
bash calculate_monthly_direct_runoff_contribution_from_urban_area.sh 2014 2010 &
bash calculate_monthly_direct_runoff_contribution_from_urban_area.sh 2015 2010 &
wait





















