
set -x

bash bash_script_for_merging_aqueduct_water_use_all_historical.sh 
bash bash_script_for_merging_aqueduct_water_use_all_rcp2p6.sh 
bash bash_script_for_merging_aqueduct_water_use_all_rcp4p5.sh 
bash bash_script_for_merging_aqueduct_water_use_all_rcp6p0.sh 
bash bash_script_for_merging_aqueduct_water_use_all_rcp8p5.sh

set +x
